import { Router } from "express";
import { dataService } from "../services/dataService.js";
import { firmsIngestService } from "../services/firmsIngestService.js";

const router = Router();

// Helper to generate minimal valid PDF buffer
function generateMinimalPdf(title, summary) {
  const safeTitle = (title || "Thermal Intelligence Report").replace(/[^\x20-\x7E]/g, "");
  const safeSummary = (summary || "Report generated by Thermogrid Intelligence Platform.").replace(/[^\x20-\x7E]/g, "");
  const stream = `BT /F1 18 Tf 50 740 Td (${safeTitle}) Tj ET\nBT /F1 11 Tf 50 700 Td (${safeSummary}) Tj ET`;
  const len = stream.length;

  const pdf = `%PDF-1.4
1 0 obj <</Type /Catalog /Pages 2 0 R>> endobj
2 0 obj <</Type /Pages /Kids [3 0 R] /Count 1>> endobj
3 0 obj <</Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources <</Font <</F1 5 0 R>>>>>> endobj
4 0 obj <</Length ${len}>>
stream
${stream}
endstream
endobj
5 0 obj <</Type /Font /Subtype /Type1 /BaseFont /Helvetica>> endobj
xref
0 6
0000000000 65535 f 
0000000010 00000 n 
0000000060 00000 n 
0000000117 00000 n 
0000000228 00000 n 
0000000${(290 + len).toString().padStart(3, "0")} 00000 n 
trailer <</Size 6 /Root 1 0 R>>
startxref
${360 + len}
%%EOF`;
  return Buffer.from(pdf, "utf-8");
}

// 1. Health
router.get("/health", (_req, res) => {
  res.json({
    data: {
      status: "ok",
      version: "1.0.0",
      capabilities: {
        live_polling: true,
        analyst_review: true,
        reports: true,
        historical_replay: true,
        gis_layers: false,
      },
    },
  });
});

// 2. Regions
router.get("/regions", (req, res) => {
  const { state } = req.query;
  const regions = dataService.getRegions(state);
  res.json({
    data: regions,
  });
});

// 3. Hotspots List
router.get("/hotspots", (req, res) => {
  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const pageSize = Math.min(5000, Math.max(1, parseInt(req.query.page_size, 10) || 10));
  const maxPoints = req.query.max_points ? parseInt(req.query.max_points, 10) : 5000;

  const allFiltered = dataService.filterHotspots(req.query);
  const total = allFiltered.length;

  const startIndex = (page - 1) * pageSize;
  const pagedItems = allFiltered.slice(startIndex, startIndex + Math.min(pageSize, maxPoints));

  res.json({
    data: pagedItems,
    meta: {
      total,
      page,
      page_size: pageSize,
      truncated: total > maxPoints,
    },
  });
});

// 4. Hotspot Detail
router.get("/hotspots/:id", (req, res) => {
  const detail = dataService.getHotspotDetail(req.params.id);
  if (!detail) {
    return res.status(404).json({ error: `Hotspot with ID '${req.params.id}' not found.` });
  }
  res.json({
    data: detail,
  });
});

// 5. Analytics Summary
router.get("/analytics/summary", (req, res) => {
  const summary = dataService.getAnalyticsSummary(req.query);
  res.json({
    data: summary,
  });
});

// 6. Analytics Trends
router.get("/analytics/trends", (req, res) => {
  const trends = dataService.getAnalyticsTrends(req.query);
  res.json({
    data: trends,
  });
});

// 7. Historical
router.get("/historical", (req, res) => {
  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const pageSize = Math.min(5000, Math.max(1, parseInt(req.query.page_size, 10) || 10));
  const maxPoints = req.query.max_points ? parseInt(req.query.max_points, 10) : 5000;

  const allFiltered = dataService.filterHotspots(req.query);
  const total = allFiltered.length;

  const startIndex = (page - 1) * pageSize;
  const pagedItems = allFiltered.slice(startIndex, startIndex + Math.min(pageSize, maxPoints));

  res.json({
    data: pagedItems,
    meta: {
      total,
      page,
      page_size: pageSize,
      truncated: total > maxPoints,
    },
  });
});

// 8. Historical Replay
router.get("/historical/replay", (req, res) => {
  const replay = dataService.getHistoricalReplay(req.query);
  res.json({
    data: replay,
  });
});

// 9. Alerts
router.get("/alerts", (req, res) => {
  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const pageSize = Math.min(100, Math.max(1, parseInt(req.query.page_size, 10) || 20));

  let items = [...dataService.alerts];
  if (req.query.risk) {
    items = items.filter((a) => a.risk === req.query.risk);
  }

  const total = items.length;
  const startIndex = (page - 1) * pageSize;
  const pagedItems = items.slice(startIndex, startIndex + pageSize);

  res.json({
    data: pagedItems,
    meta: {
      total,
      page,
      page_size: pageSize,
    },
  });
});

// 10. Reports List
router.get("/reports", (req, res) => {
  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const pageSize = Math.min(100, Math.max(1, parseInt(req.query.page_size, 10) || 20));

  const total = dataService.reports.length;
  const startIndex = (page - 1) * pageSize;
  const pagedItems = dataService.reports.slice(startIndex, startIndex + pageSize);

  res.json({
    data: pagedItems,
    meta: {
      total,
      page,
      page_size: pageSize,
    },
  });
});

// 11. Create Report
router.post("/reports", (req, res) => {
  const id = `rep_${String(dataService.reports.length + 1).padStart(3, "0")}`;
  const now = new Date().toISOString();

  const newReport = {
    id,
    name: req.body?.name || `Thermal Surveillance Report — ${now.slice(0, 10)}`,
    status: "ready",
    created_at: now,
    summary: `Comprehensive FIRMS/Sentinel-2 thermal report generated from current filter criteria. Total evaluated records: ${dataService.hotspots.length}.`,
  };

  dataService.reports.unshift(newReport);

  res.status(201).json({
    data: newReport,
  });
});

// 12. Get Report
router.get("/reports/:id", (req, res) => {
  const report = dataService.reports.find((r) => r.id === req.params.id);
  if (!report) {
    return res.status(404).json({ error: "Report not found" });
  }
  res.json({
    data: report,
  });
});

// 13. Download Report PDF
router.get("/reports/:id/download", (req, res) => {
  const report = dataService.reports.find((r) => r.id === req.params.id);
  const pdfBuffer = generateMinimalPdf(
    report?.name || "Thermogrid Intelligence Report",
    report?.summary || "Automated geospatial anomaly overview."
  );

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${req.params.id}.pdf"`);
  res.send(pdfBuffer);
});

// 14. Analyst Review
router.post("/analyst-review", (req, res) => {
  const { hotspot_id, classification, note, reviewer } = req.body;

  if (!hotspot_id || !classification || !reviewer) {
    return res.status(400).json({ error: "Missing required fields: hotspot_id, classification, reviewer" });
  }

  const verification = dataService.saveReview(hotspot_id, classification, reviewer, note || "Reviewed by analyst");
  if (!verification) {
    return res.status(404).json({ error: "Hotspot not found" });
  }

  res.json({
    data: verification,
  });
});

// 15. Live Ingestion Trigger & Status
router.post("/ingest/firms", async (_req, res) => {
  try {
    const result = await firmsIngestService.ingestLiveFirmsData();
    res.json({
      data: {
        status: "success",
        ingested_count: result.count,
        source: result.source,
        total_active_hotspots: dataService.hotspots.length,
        timestamp: new Date().toISOString(),
        next_scheduled: firmsIngestService.nextRun,
      },
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get("/ingest/status", (_req, res) => {
  res.json({
    data: firmsIngestService.getStatus(),
  });
});

export default router;
